"""migrations

Revision ID: 221b2d809783
Revises: 
Create Date: 2019-08-31 04:17:18.491821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221b2d809783'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('staff_name', sa.String(length=70), nullable=True))
    op.create_index(op.f('ix_routes_staff_name'), 'routes', ['staff_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_staff_name'), table_name='routes')
    op.drop_column('routes', 'staff_name')
    # ### end Alembic commands ###
