"""migrations

Revision ID: 3aa745ab7222
Revises: b1e2e84ca21a
Create Date: 2019-08-31 02:54:50.114953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa745ab7222'
down_revision = 'b1e2e84ca21a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('staffs_role_id_fkey', 'staffs', type_='foreignkey')
    op.create_foreign_key(None, 'staffs', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staffs', type_='foreignkey')
    op.create_foreign_key('staffs_role_id_fkey', 'staffs', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
