"""migrations

Revision ID: 41af858965d1
Revises: b1e2e84ca21a
Create Date: 2019-08-31 02:45:05.963370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41af858965d1'
down_revision = 'b1e2e84ca21a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_constraint('staffs_role_id_fkey', 'staffs', type_='foreignkey')
    op.drop_column('staffs', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffs', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('staffs_role_id_fkey', 'staffs', 'roles', ['role_id'], ['id'])
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('name', name='roles_name_key')
    )
    # ### end Alembic commands ###
