"""empty message

Revision ID: 561fa2c92c71
Revises: ec63f02b17c7
Create Date: 2019-08-28 09:36:10.198857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561fa2c92c71'
down_revision = 'ec63f02b17c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_column('owners', 'role')
    op.drop_column('owners', 'password_hash')
    op.drop_constraint('staffs_role_id_fkey', 'staffs', type_='foreignkey')
    op.drop_column('staffs', 'role_id')
    op.add_column('trips', sa.Column('conductor', sa.String(length=255), nullable=True))
    op.add_column('trips', sa.Column('driver', sa.String(length=255), nullable=True))
    op.add_column('trips', sa.Column('staff_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_trips_conductor'), 'trips', ['conductor'], unique=False)
    op.create_index(op.f('ix_trips_driver'), 'trips', ['driver'], unique=False)
    op.create_index(op.f('ix_trips_staff_name'), 'trips', ['staff_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_staff_name'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver'), table_name='trips')
    op.drop_index(op.f('ix_trips_conductor'), table_name='trips')
    op.drop_column('trips', 'staff_name')
    op.drop_column('trips', 'driver')
    op.drop_column('trips', 'conductor')
    op.add_column('staffs', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('staffs_role_id_fkey', 'staffs', 'roles', ['role_id'], ['id'])
    op.add_column('owners', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('owners', sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('name', name='roles_name_key')
    )
    # ### end Alembic commands ###
