"""adds Assets model

Revision ID: 5e0de60c243a
Revises: 420f476ef089
Create Date: 2019-08-22 12:51:20.295362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0de60c243a'
down_revision = '420f476ef089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_plate', sa.String(length=10), nullable=True),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_number_plate'), 'assets', ['number_plate'], unique=False)
    op.create_index(op.f('ix_assets_route'), 'assets', ['route'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_route'), table_name='assets')
    op.drop_index(op.f('ix_assets_number_plate'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
