"""migrations

Revision ID: 9caed60a7d86
Revises: 221b2d809783
Create Date: 2019-09-01 17:47:10.282082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9caed60a7d86'
down_revision = '221b2d809783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'routes', 'owners', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_column('routes', 'owner')
    # ### end Alembic commands ###
