"""migrations

Revision ID: b714a7e1164b
Revises: 206c7a5c44a6
Create Date: 2019-08-28 23:54:21.964853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b714a7e1164b'
down_revision = '206c7a5c44a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_routes_fare'), 'routes', ['fare'], unique=False)
    op.create_index(op.f('ix_routes_passengers'), 'routes', ['passengers'], unique=False)
    op.drop_constraint('routes_fare_key', 'routes', type_='unique')
    op.drop_constraint('routes_passengers_key', 'routes', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('routes_passengers_key', 'routes', ['passengers'])
    op.create_unique_constraint('routes_fare_key', 'routes', ['fare'])
    op.drop_index(op.f('ix_routes_passengers'), table_name='routes')
    op.drop_index(op.f('ix_routes_fare'), table_name='routes')
    # ### end Alembic commands ###
